apiVersion: v1
kind: Pod
metadata:
  name: wide-ep-helper
  labels:
    llm-d.ai/role: testing-helper
spec:
  serviceAccountName: wide-ep
  volumes:
    - name: lustre
      persistentVolumeClaim:
        claimName: lustre-pvc-vllm
  containers:
    - name: helper
      image: busybox:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - mountPath: /mnt/lustre/vllm-vlm-elvircrn
          name: lustre
